name: Makefile CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README*'
      - 'assets/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README*'
      - 'assets/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: requirements
      run: sudo apt-get install libxrandr-dev

    - name: build
      run: make
